hello: ENC[AES256_GCM,data:EVBXJzJ6qEKHl6xEEShRcWl9Z4MD/qVS4/RNegLiftu/A1DWmnplykpPUpbs9Q==,iv:BO9BhCLnGOgqqGxxJ/hTB9BQ8bZ2j+UejGg61+aZd8k=,tag:R9pz/UEwbe6qerqT/ryLkQ==,type:str]
spotifyd: ENC[AES256_GCM,data:x7uTifX6N8M=,iv:74Pzd4OscOjK80RDx6SUaHr0Yyd1UGmnGPiqV4QNOV8=,tag:QxVHISDDrfxzHqz5+fBxPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dl2ldz7s96plfwl0vaur78cy6dwq0tv2726zq5frfykvxkdh2qcqmn6flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU3VXclJ3amg0alFxaUk0
            cFczUEFVMW9VNUdYWXRhelZvdzNYckRNbFRBCmExajBMa2hObWw0WmpiQVg1MTlU
            THZMa3JidlZNcGI3SGE5VlIxR3pDZmcKLS0tIC9OSlZpQWJHUW9wcU8ybkozYU1i
            bGtxaEhiNGFMclhtNW4yak1JRUxacWMK0td610Rkhye8+NW/IjSUqVI9h93grapY
            VSpwMf7P4WBewkL7CVNg3n6/49ipb1L2TK6VHxoLNgBcdt7mdQlOgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zswlplhkdu0pzx08uruxwq7lgumvtahrnllcs34xpuxru9xqy3aqtjrkhv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa1FuQS9xcWF4dW5QQldJ
            UFV4THp0S051UGxFa3RzQk1vSk5lQjljdGdZCjY3V1RPMG1GKzJQUzNrWDBHZjNo
            SzNObTZLVW5ScTBxazJvZDNBYXhNdHMKLS0tICsvdWlVaFpzcEFqcTJ3bTF6d2Ix
            SGRZdndYVVNKTnVMZUFIRkJyenFyOXMKpCHomOSP0EvXkGJgneySYEJoNJ8Da6Em
            Se3vSkSyhvyENmkDLfwMBiPhfiZ+UVKlIGZlYxCEH9XywzuAvpneOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:CvhapCRPkwoCWlGi7pqccPI/UamjKhRsD7/91V/bg0FugmB4TS6VApOPoRDCqm093phnBqaCKQWU/gGVTrK10Ja3pfG01nvq6/TWGErFcO6h8XvbfydyxIhHvjSengyLrpn6xdT9qv66m54C6HorU2Q3oTNDgu1bUxoE1GUvldU=,iv:20y21KS63wJm9zieIVrBB05UZ0eKLBh6zBWZQx7xJt4=,tag:0V705dDzKCuYUSbTR2f4NQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
