freshrss: ENC[AES256_GCM,data:os6eT81gCVUtSwodMG7FHpu2aKYH,iv:+4Z1c91nNncpTXIUXDHZ4E1/qyzY5vmxUlgUC8kFWCE=,tag:R+JUiChWtj8o6uzjnL7Wfg==,type:str]
miniflux: ENC[AES256_GCM,data:6/qpxzI1PdSTCHmn6s94NbcYIUOYe/29yorOy3iNeIf2kYeOJUzAYvTrUkWX0HWcWmUvnYGhIw==,iv:VDBcPEYAP+7lT2uSxQ1cOfbMo/JmH2chXEfAwffxblw=,tag:8cw5QOhWzR2ppmk6rsQLqg==,type:str]
cloudflare: ENC[AES256_GCM,data:iDgeNSHKoHwN/MDghcvXMA0+UZxjLFgYB5jnQas5DfvhXYBPFHCkT4rAqk8RhwREDXLP7Bh+oItpTgaivA==,iv:ANQDdgffe0L1IFdlEp9pd+WGE/hxO2J2tiFC5p7R5do=,tag:uw+AWrcfLKbJXlRIaSqGSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dl2ldz7s96plfwl0vaur78cy6dwq0tv2726zq5frfykvxkdh2qcqmn6flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQi9xRzVDdll5bDZyTC9w
            MFpTUjl3aWk2ODNqdkJyTUxzcVJlKzNoaTFBCmJtWnRyanZRQTZWVzB4dXA1WGlw
            UzN1QjRmbkc2U1ZyTHVRL2YwazlqQ1UKLS0tIFFZNFRjaUJlRTd6UGMyeURRK3or
            ZnFsODY2aUV0NVYyTXRhSjQxYU5EZ3MK+sFiAjf/Qmi/nAA2SrY/aNnobpFWdpYd
            H5VsWYzy8yskpzmRumUKTtfVSJHBobxZPb0wl7kmgT1LsWzFr0i+hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zswlplhkdu0pzx08uruxwq7lgumvtahrnllcs34xpuxru9xqy3aqtjrkhv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZi9XL2hqOENtYXN4akJq
            N2tSQ2lRYXM4WEhkbjZJRndxQVF2RzFqMFVNCmN2SlBWTElINXNwNnNoYTBsbURW
            WGhRR0hPRHNVMzJsMElrWkdiSzFQaGMKLS0tIHRpZWhJbW5QVmgzTDlQQmZvUkE4
            VGU3VW5kaWNkZzJxNzVUZkV3N3NyK0kK1Geg6xtfW7l7fek37+LBlu4V0LqR9zti
            E4iegV1+c8VZeNW3fyBYAriElntVyMpkirDsGUFJ1Zs1ybmM/CKv9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T18:52:40Z"
    mac: ENC[AES256_GCM,data:rAh/d1VfnY+rx1yhYXOU0D2svsstxl40U0k3FX+VGVvRDl2nFt6SC+NkscX5LAT97rc1zhgcHWZw4a5gs0r2GLNycrreLnenrw7Z6V0MNT8r5JzrJxDhOz8e0kyLXw/uYknrV10hDqzv5JnWS3+6f/EGW7M3RNOiaD0CgdjjkuM=,iv:KBjtIOUKr3/c+eQPq3IF1kdOHKeBtsaPZ2x7/GyKrwg=,tag:UaQGyOYL7kEBT5/2RPfZ/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
