freshrss: ENC[AES256_GCM,data:os6eT81gCVUtSwodMG7FHpu2aKYH,iv:+4Z1c91nNncpTXIUXDHZ4E1/qyzY5vmxUlgUC8kFWCE=,tag:R+JUiChWtj8o6uzjnL7Wfg==,type:str]
miniflux: ENC[AES256_GCM,data:6/qpxzI1PdSTCHmn6s94NbcYIUOYe/29yorOy3iNeIf2kYeOJUzAYvTrUkWX0HWcWmUvnYGhIw==,iv:VDBcPEYAP+7lT2uSxQ1cOfbMo/JmH2chXEfAwffxblw=,tag:8cw5QOhWzR2ppmk6rsQLqg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dl2ldz7s96plfwl0vaur78cy6dwq0tv2726zq5frfykvxkdh2qcqmn6flk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQi9xRzVDdll5bDZyTC9w
        MFpTUjl3aWk2ODNqdkJyTUxzcVJlKzNoaTFBCmJtWnRyanZRQTZWVzB4dXA1WGlw
        UzN1QjRmbkc2U1ZyTHVRL2YwazlqQ1UKLS0tIFFZNFRjaUJlRTd6UGMyeURRK3or
        ZnFsODY2aUV0NVYyTXRhSjQxYU5EZ3MK+sFiAjf/Qmi/nAA2SrY/aNnobpFWdpYd
        H5VsWYzy8yskpzmRumUKTtfVSJHBobxZPb0wl7kmgT1LsWzFr0i+hw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zswlplhkdu0pzx08uruxwq7lgumvtahrnllcs34xpuxru9xqy3aqtjrkhv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZi9XL2hqOENtYXN4akJq
        N2tSQ2lRYXM4WEhkbjZJRndxQVF2RzFqMFVNCmN2SlBWTElINXNwNnNoYTBsbURW
        WGhRR0hPRHNVMzJsMElrWkdiSzFQaGMKLS0tIHRpZWhJbW5QVmgzTDlQQmZvUkE4
        VGU3VW5kaWNkZzJxNzVUZkV3N3NyK0kK1Geg6xtfW7l7fek37+LBlu4V0LqR9zti
        E4iegV1+c8VZeNW3fyBYAriElntVyMpkirDsGUFJ1Zs1ybmM/CKv9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-01-04T03:21:20Z"
  mac: ENC[AES256_GCM,data:yH8xC5opjBzZ9VU1KnCXwWSBenxj5tkUZEh3NN4j5WRaE01hCdVMaGGEkgUFgq/T+npoTj9cjbKMy3AHB+Dt8MLVgoKqToGu9q5prUl/xGFN9mMkV66PAAo5WG+CBFlDNV10q4J0qge3LzQucGiHclxvgmsqb3RzfmsGvXtMfWo=,iv:KxJPCwycs30dq6fkSiqH/vge8fW6/y0CKH/xSPgnXX0=,tag:Bicl6kcLgwEsqK4q1L0yLg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
