hello: ENC[AES256_GCM,data:EVBXJzJ6qEKHl6xEEShRcWl9Z4MD/qVS4/RNegLiftu/A1DWmnplykpPUpbs9Q==,iv:BO9BhCLnGOgqqGxxJ/hTB9BQ8bZ2j+UejGg61+aZd8k=,tag:R9pz/UEwbe6qerqT/ryLkQ==,type:str]
spotifyd: ENC[AES256_GCM,data:x7uTifX6N8M=,iv:74Pzd4OscOjK80RDx6SUaHr0Yyd1UGmnGPiqV4QNOV8=,tag:QxVHISDDrfxzHqz5+fBxPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dl2ldz7s96plfwl0vaur78cy6dwq0tv2726zq5frfykvxkdh2qcqmn6flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OWhubGYrYVMrYzFabXF3
            eGVuUWFQV3VHS3l0Z3JDZGNjWWt4ZncxMmlVCnVHejVDZnRoaTg5dGhoZmc0Ui93
            cHFDeHNkYUFsbjhXVjVoSFg4NnFxN1kKLS0tIC9kbU9xTnNGK0Z6RWh3OE5qOHhy
            R1BIdzJZeUtBUDdtVjVuai9kTEcvZ1EKGWp2nb2g67ljd8q4JlwfriujBvweBnj5
            J7AE0r0Z7DxS/GrLmRvnguCZMrcvFo4huz1E0vDDdHaI6SCgqGVNvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8eeycvfjaly7ngeukatevj70g428h4kvk3qw8ygpl8k2wlvzu0sd0x5ju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTTdoSzB6MUdtYXZKMDUz
            amVFTUVwalJra2VKSHZZS3dSZE9hNDQzUVVnCllkWmhLRHdJVEhqSXlPS0pLWk1O
            eU9qa2VURDJPRmVZUWFDL1VWMERlNDAKLS0tIDVUZzlWeTFXSUM2Qnc0cVBMQUpB
            eWtVMSt1bWVjOWZlQ3hWOGN5TkNrVlUKfvH4tbAreXNyqprERxGqGbFFOi2C4lE/
            S6WX21AafDpCn1/H/64ViIyc1fQsGsV6VnQcaChPixg3Kn0RWQ/fTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:CvhapCRPkwoCWlGi7pqccPI/UamjKhRsD7/91V/bg0FugmB4TS6VApOPoRDCqm093phnBqaCKQWU/gGVTrK10Ja3pfG01nvq6/TWGErFcO6h8XvbfydyxIhHvjSengyLrpn6xdT9qv66m54C6HorU2Q3oTNDgu1bUxoE1GUvldU=,iv:20y21KS63wJm9zieIVrBB05UZ0eKLBh6zBWZQx7xJt4=,tag:0V705dDzKCuYUSbTR2f4NQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
