freshrss: ENC[AES256_GCM,data:os6eT81gCVUtSwodMG7FHpu2aKYH,iv:+4Z1c91nNncpTXIUXDHZ4E1/qyzY5vmxUlgUC8kFWCE=,tag:R+JUiChWtj8o6uzjnL7Wfg==,type:str]
miniflux: ENC[AES256_GCM,data:6/qpxzI1PdSTCHmn6s94NbcYIUOYe/29yorOy3iNeIf2kYeOJUzAYvTrUkWX0HWcWmUvnYGhIw==,iv:VDBcPEYAP+7lT2uSxQ1cOfbMo/JmH2chXEfAwffxblw=,tag:8cw5QOhWzR2ppmk6rsQLqg==,type:str]
caddy: ENC[AES256_GCM,data:iVKiBUqca26DJdhNrdmi2uZW3glrXNK7aFoEJ9V7uLX9x8pxO2rrbtuQgcG3ThglX+56BU/qlFBmCO/S+fviHl694ZRT8V3Ue3jU,iv:VwGev8MPlEY5ujXV7oTUjNYTR5UqYFHovM1aKfnD2Yw=,tag:PcmMbCl28gHS8phEvujQTQ==,type:str]
tailscaleService: ENC[AES256_GCM,data:+B7r2aIX6xJw4sAkiIL39MCY/Jm+5LEE+4r/KvMypzn9HpTlDmpS5qcJwc/EnAv54vdtJl2edjvK,iv:3Q+2vH1AF85kbE8cLops7hj6GmlF/bu5aZQmvjJRz8U=,tag:eGvz8rurpbdF3aDaCRvzng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dl2ldz7s96plfwl0vaur78cy6dwq0tv2726zq5frfykvxkdh2qcqmn6flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQi9xRzVDdll5bDZyTC9w
            MFpTUjl3aWk2ODNqdkJyTUxzcVJlKzNoaTFBCmJtWnRyanZRQTZWVzB4dXA1WGlw
            UzN1QjRmbkc2U1ZyTHVRL2YwazlqQ1UKLS0tIFFZNFRjaUJlRTd6UGMyeURRK3or
            ZnFsODY2aUV0NVYyTXRhSjQxYU5EZ3MK+sFiAjf/Qmi/nAA2SrY/aNnobpFWdpYd
            H5VsWYzy8yskpzmRumUKTtfVSJHBobxZPb0wl7kmgT1LsWzFr0i+hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zswlplhkdu0pzx08uruxwq7lgumvtahrnllcs34xpuxru9xqy3aqtjrkhv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZi9XL2hqOENtYXN4akJq
            N2tSQ2lRYXM4WEhkbjZJRndxQVF2RzFqMFVNCmN2SlBWTElINXNwNnNoYTBsbURW
            WGhRR0hPRHNVMzJsMElrWkdiSzFQaGMKLS0tIHRpZWhJbW5QVmgzTDlQQmZvUkE4
            VGU3VW5kaWNkZzJxNzVUZkV3N3NyK0kK1Geg6xtfW7l7fek37+LBlu4V0LqR9zti
            E4iegV1+c8VZeNW3fyBYAriElntVyMpkirDsGUFJ1Zs1ybmM/CKv9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T20:09:58Z"
    mac: ENC[AES256_GCM,data:MWnj2FG13IWyzSeckxH0td3IFmz/c6rYSASrBfs3w6a+qX4VCNw6JBgh9kVF6Ki/tlDIpIz1HFXKSORBITZNyA0FjmXDuPMXFMHXP+2CoNUULZtZLOhRolYrGkjioSBp7tHtaW8HgnvzZ056GmMYlrJFRyROO+2CWIZ6Gbzt2XY=,iv:m5XSWM+CxrE2T0N6h5JGMYYbO4szeXNPmLUIXCBMBm8=,tag:B2SIiDoPGHLf1EBIQjrnlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
